# Find3D Material Search - Kubernetes Services

apiVersion: v1
kind: Service
metadata:
  name: find3d-app-service
  namespace: find3d
  labels:
    app: find3d-material-search
    component: frontend
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 443
    targetPort: 8080
    protocol: TCP
    name: https
  selector:
    app: find3d-material-search
    component: frontend
  sessionAffinity: None

---
apiVersion: v1
kind: Service
metadata:
  name: find3d-api-service
  namespace: find3d
  labels:
    app: find3d-material-search
    component: api
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: find3d-material-search
    component: api
  sessionAffinity: None

---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: find3d
  labels:
    app: find3d-material-search
    component: redis
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
  selector:
    app: find3d-material-search
    component: redis
  sessionAffinity: None

---
# Headless service for Redis cluster
apiVersion: v1
kind: Service
metadata:
  name: redis-headless
  namespace: find3d
  labels:
    app: find3d-material-search
    component: redis
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
    name: redis
  selector:
    app: find3d-material-search
    component: redis